---
resources:
- name: pool-pks-locks
  type: pool
  source:
    uri: git@github.com:pivotal-cf/pks-locks.git
    pool: gcp-flannel-om28-terraform
    branch: master
    private_key: ((pks-bot-ssh-key.private_key))

- name: git-kubo-odb-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf/kubo-odb-ci
    branch: master
    private_key: ((pks-bot-ssh-key.private_key))

- name: git-pks-kubernetes-release
  type: git
  source:
    uri: git@github.com:pivotal-cf/pks-kubernetes-release.git
    branch: master
    private_key: ((git-ssh-key.private_key))
    ignore_paths: [ci]

# redeclare the same git resource to isolate the CI as something that can rapidly change
#  without triggering or requiring passed
- name: git-boshcycle-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf/pks-kubernetes-release.git
    branch: master
    private_key: ((git-ssh-key.private_key))
    paths: [ci]

- name: git-pks-kubernetes-windows-release
  type: git
  source:
    uri: git@github.com:pivotal-cf/pks-kubernetes-windows-release.git
    branch: master
    private_key: ((git-ssh-key.private_key))

- name: gcp-linux-stemcell
  source:
    name: bosh-google-kvm-ubuntu-xenial-go_agent
    version_family: "456.30"
  type: bosh-io-stemcell

- name: gcp-windows-stemcell
  source:
    name: bosh-google-kvm-windows2019-go_agent
    version_family: "2019.12"
  type: bosh-io-stemcell

jobs:
- name: run-unit-tests
  plan:
    - in_parallel:
        - get: git-boshcycle-ci
        - get: git-pks-kubernetes-release
        - get: git-pks-kubernetes-windows-release
    - task: run-tests-kubo-release
      privileged: true
      input_mapping:
        bosh-release: git-pks-kubernetes-release
      file: git-boshcycle-ci/ci/tasks/run-tests/task.yml
    - task: run-tests-kubo-release-windows
      privileged: true
      input_mapping:
        bosh-release: git-pks-kubernetes-windows-release
      file: git-boshcycle-ci/ci/tasks/run-tests/task.yml

- name: claim-lock
  max_in_flight: 1
  plan:
  - in_parallel:
    - get: git-kubo-odb-ci
    - get: git-pks-kubernetes-release
      passed: [ 'run-unit-tests' ]
      trigger: true
    - get: git-pks-kubernetes-windows-release
      passed: [ 'run-unit-tests' ]
      trigger: true
    - get: pool-pks-locks
  - put: pool-pks-locks
    params:
      acquire: true

- name: upload-kubo-release
  plan:
  - in_parallel:
    - get: git-kubo-odb-ci
    - get: git-boshcycle-ci
    - get: git-pks-kubernetes-release
#      passed: [ 'claim-lock' ]
    - get: pool-pks-locks
      trigger: true
      passed: [ 'claim-lock' ]
  - task: create-bosh-config
    tags: ['gcp']
    input_mapping:
      locks-repo: pool-pks-locks
    file: git-kubo-odb-ci/tasks/create-bosh-config.yml
  - task: upload-kubo-release
    privileged: true
    file: git-boshcycle-ci/ci/minimum-release-verification/upload-kubo-release/task.yml

- name: upload-kubo-release-windows
  plan:
  - in_parallel:
    - get: git-kubo-odb-ci
    - get: git-boshcycle-ci
    - get: pool-pks-locks
      trigger: true
      passed: [ 'claim-lock' ]
    - get: git-pks-kubernetes-windows-release
      passed: [ 'claim-lock' ]
  - task: create-bosh-config
    tags: ['gcp']
    input_mapping:
      locks-repo: pool-pks-locks
    file: git-kubo-odb-ci/tasks/create-bosh-config.yml
  - task: upload-kubo-release
    privileged: true
    file: git-boshcycle-ci/ci/minimum-release-verification/upload-kubo-release-windows/task.yml

- name: upload-linux-stemcell
  plan:
  - in_parallel:
    - get: git-kubo-odb-ci
    - get: git-boshcycle-ci
    - get: gcp-linux-stemcell
    - get: pool-pks-locks
      trigger: true
      passed: [ 'claim-lock' ]
  - task: create-bosh-config
    tags: ['gcp']
    input_mapping:
      locks-repo: pool-pks-locks
    file: git-kubo-odb-ci/tasks/create-bosh-config.yml
  - task: upload-linux-stemcell
    privileged: true
    input_mapping:
      stemcell: gcp-linux-stemcell
    file: git-boshcycle-ci/ci/minimum-release-verification/upload-stemcell/task.yml

- name: upload-windows-stemcell
  plan:
  - in_parallel:
    - get: git-kubo-odb-ci
    - get: git-boshcycle-ci
    - get: gcp-windows-stemcell
    - get: pool-pks-locks
      trigger: true
      passed: [ 'claim-lock' ]
  - task: create-bosh-config
    tags: ['gcp']
    input_mapping:
      locks-repo: pool-pks-locks
    file: git-kubo-odb-ci/tasks/create-bosh-config.yml
  - task: upload-windows-stemcell
    privileged: true
    input_mapping:
      stemcell: gcp-windows-stemcell
    file: git-boshcycle-ci/ci/minimum-release-verification/upload-stemcell/task.yml

- name: deploy-manifest
  plan:
  - in_parallel:
    - get: git-kubo-odb-ci
    - get: git-boshcycle-ci
    - get: pool-pks-locks
      trigger: true
      passed:
        - 'upload-kubo-release'
        - 'upload-kubo-release-windows'
        - 'upload-linux-stemcell'
        - 'upload-windows-stemcell'
    - get: git-pks-kubernetes-release
      passed: [ 'upload-kubo-release' ]
    - get: git-pks-kubernetes-windows-release
      passed: [ 'upload-kubo-release-windows' ]
  - task: create-bosh-config
    tags: ['gcp']
    input_mapping:
      locks-repo: pool-pks-locks
    file: git-kubo-odb-ci/tasks/create-bosh-config.yml
  - task: deploy-release
    privileged: true
    file: git-boshcycle-ci/ci/minimum-release-verification/deploy-manifest/task.yml

- name: print-component-versions
  plan:
  - in_parallel:
    - get: git-kubo-odb-ci
    - get: git-boshcycle-ci
    - get: pool-pks-locks
      trigger: true
      passed: [ 'deploy-manifest' ]
    - get: git-pks-kubernetes-release
      passed: [ 'deploy-manifest' ]
    - get: git-pks-kubernetes-windows-release
      passed: [ 'deploy-manifest' ]
  - task: create-bosh-config
    tags: ['gcp']
    input_mapping:
      locks-repo: pool-pks-locks
    file: git-kubo-odb-ci/tasks/create-bosh-config.yml
  - task: print-component-versions
    privileged: true
    file: git-boshcycle-ci/ci/minimum-release-verification/print-component-versions/task.yml

- name: cleanup
  plan:
  - in_parallel:
    - get: git-kubo-odb-ci
    - get: git-boshcycle-ci
    - get: pool-pks-locks
      trigger: true
      passed: [ 'print-component-versions' ]
    - get: git-pks-kubernetes-release
      passed: [ 'print-component-versions' ]
    - get: git-pks-kubernetes-windows-release
      passed: [ 'print-component-versions' ]
  - task: create-bosh-config
    tags: ['gcp']
    input_mapping:
      locks-repo: pool-pks-locks
    file: git-kubo-odb-ci/tasks/create-bosh-config.yml
  - task: delete-release
    privileged: true
    file: git-boshcycle-ci/ci/minimum-release-verification/cleanup/task.yml
  - put: pool-pks-locks
    params:
      release: pool-pks-locks
